name: Generate Sitemap
on:
  push:
    branches: [ main ] # Trigger on pushes to main branch
    paths:
      - '**.html' # Only run when HTML files change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Sitemap
        run: |
          # Find all HTML files (excluding 404.html)
          echo "<?xml version='1.0' encoding='UTF-8'?>" > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          find . -name "*.html" -not -name "404.html" | while read file; do
            path="${file#./}"
            echo "  <url><loc>https://baguettemaison.com/${path}</loc></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Commit and Push Sitemap
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap" || echo "No changes to commit"
          git push
